export const blogs = [
    {
        id: 1,
        img: "https://belletrist.qodeinteractive.com/wp-content/uploads/2020/08/Blog-single-img6-417x292.jpg",
        slug: "1",
        date: "On 19. Aug. 2020.",
        title: "Get ready for Holiday on a Christmas week",
        category: "POEM",
        comments: "1 COMMENT",
    },
    {
        id: 2,
        img: "https://belletrist.qodeinteractive.com/wp-content/uploads/2020/08/Blog-single-img7-417x292.jpg",
        date: "On 20. Aug. 2020.",
        slug: "2",
        title: "Stream of thought in new age narratives",
        category: "POEM",
        comments: "2 COMMENTS",
    },
    {
        id: 3,
        img: "https://belletrist.qodeinteractive.com/wp-content/uploads/2020/08/Blog-single-img8-417x292.jpg",
        date: "On 21. Aug. 2020.",
        slug: "3",
        title: "The beginner’s guide to fountain pen inks",
        category: "POEM",
        comments: "3 COMMENT",
    },
    {
        id: 1,
        img: "https://belletrist.qodeinteractive.com/wp-content/uploads/2020/08/Blog-single-img9-417x292.jpg",
        date: "On 19. Aug. 2020.",
        slug: "4",
        title: "Get ready for Holiday on a Christmas week",
        category: "POEM",
        comments: "4 COMMENT",
    },
    {
        id: 2,
        img: "https://belletrist.qodeinteractive.com/wp-content/uploads/2020/08/h1-img-1.jpg",
        date: "On 20. Aug. 2020.",
        slug: "5",
        title: "Stream of thought in new age narratives",
        category: "POEM",
        comments: "5 COMMENTS",
    },
    {
        id: 3,
        img: "https://belletrist.qodeinteractive.com/wp-content/uploads/2020/08/Blog-single-img15-305x198.jpg",
        date: "On 21. Aug. 2020.",
        slug: "6",
        title: "The beginner’s guide to fountain pen inks",
        category: "POEM",
        comments: "6 COMMENT",
    }]